### ISSUE TITLE
Trackpad on Vivobook S510UN

### ISSUE THREAD

**Issue by yuvrajharod** [JoK3rLeE/Asus-S510UQ-BQ178T#2]
Hello,

I actually have a vivobook S510UN from Asus and I was unable to find a solution for my non-working trackpad(Elan 1300) can you please help me with what all needs to be done. I've pretty much used all the kexts and as I m very new to the hackintosh, GPIO pinning and related things were getting hard on me. As you're a well-experienced person in the field and have the same working trackpad, can you please help me build my Trackpad patch? I'll really appreciate your help mate

Thanks

**Comment by JoK3rLeE** [comment]
Did you try my EFI config? Your hardware should be the same as mine (ELAN1300) and it will work without any patches.

If you use your own ACPI patches, you may use whatnameisit I2C patch :https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.7-Hackintosh/blob/master/OpenCore%20EFI/EFI/OC/ACPI/SSDT-I2C1_USTP.aml

**Comment by yuvrajharod** [comment]
I see, are you using poller mode to make the trackpad work??

**Comment by yuvrajharod** [comment]
I tried in poller mode using I2c SSDT for UTP but that didn't worked for me, can you please just guide me through the process as I can't replace the EFI as I have a complete different gen CPU and GPU

I'll be really grateful to you if you can put in the complete method for OC

THnks

**Comment by JoK3rLeE** [comment]
> I tried in poller mode using I2c SSDT for UTP but that didn't worked for me, can you please just guide me through the process as I can't replace the EFI as I have a complete different gen CPU and GPU
> 
> I'll be really grateful to you if you can put in the complete method for OC
> 
> THnks

Sry for the late reply was handling my exam. 
Can you send me your whole config (EFI Folder better )? As far as I know, different gen CPU still works (you can refer whatnameisit repo, his processor is 8th gen and also you can refer to https://www.tonymacx86.com/threads/guide-new-voodooi2c-asus-vivobook-s15-x510uar-10-13.245445/ )  you may try my whole EFI by using bootable USB installer to test whether it bootable and trackpad works or not. 
Trackpad is dependant on VoodooI2C, I'm not sure you added it correctly in the kernel.

**Comment by yuvrajharod** [comment]
Okay so I was unable to use DSDT editing first but later understood with time and can see the other link worthful, I tried it once but couldn't bring it to work. I guess you said it better, I'm attaching an external link with my EFI folder in it. can you please just check what's wrong with it... I really appreciate all your efforts and wish you all the best with your exams.

https://easyupload.io/0vn4rj
It's pwd protected (Fill)

**Comment by JoK3rLeE** [comment]
I can't access your file, maybe you can try to upload it here or email me

 jok3rle3@gmail.com

**Comment by JoK3rLeE** [comment]
It seems like you inject your trackpad with two different controllers, I removed it you may replace your current config. 
Also, place VoodooInput.kext into kext folder 
[Config and kext.zip](https://github.com/JoK3rLeE/Asus-S510UQ-BQ178T/files/5739978/Config.and.kext.zip)

**Comment by yuvrajharod** [comment]
Umm, I tried it, unfortunately, no luck. You can see it anytime you have some spare hours as it's a bit time-consuming. Thanks for everything though.

**Comment by JoK3rLeE** [comment]
> Umm, I tried it, unfortunately, no luck. You can see it anytime you have some spare hours as it's a bit time-consuming. Thanks for everything though.

Your EFI quite bloated, I'll try to boot your EFI to see what's the issue

**Comment by yuvrajharod** [comment]
Sure I'll wait for you!

**Comment by JoK3rLeE** [comment]
> Sure I'll wait for you!

I have some good news, I tried to rewrite the new config for your EFI and trackpad is working now! 
I'll upload it once I done clean up your ACPI (Some are duplicated)

**Comment by yuvrajharod** [comment]
Hey mate, it was such a mess for me, I just can't tell you how long I've waited for my trackpad to work and I was forced to use an external mouse for no good reason. I just can't describe how thank thankful I'm to you. Really a big thanks for taking out all the time and arranging and naming all the contents of my EFI. I just can't thank you enough. And finally, my trackpad works as you said. I first when read couldn't believe it and thought okay it would be another fail trail but this time I could find some good luck of mine or I can say you're good to work. I really really thank you once again for all the helpmate. 


I just can't thank you enough and can't think of anything else apart from thanking you for the help you've done to me. If there's anything I can help you with, please tell me anytime, I'll definitely try if I can add any value to your life. Also if you can help me just a little more. I was trying to use the trackpad setting a bit but I think I m confused a bit. So usually whenever I click on chrome it opens up with all the windows or activated window but this time it didn't. When I use a mouse it does performs the way it should but with a trackpad, it says no window activated. Is this some setting issue I need to change as I m using the trackpad for the first time in the mac. it would be great if you can just mention this. Also can you please mention where was I wrong? I was actually looking for a solution for more than 2 weeks now but couldn't find an appropriate reason why wasn't it working. I'm just a little bit curious to know what I did wrong even though I mostly built my EFI on my own with dortiana guide. 

Again one big thanks to you mate you took out time for me even during your xms, 


Thanks😅

**Comment by JoK3rLeE** [comment]
You're welcome mate! Btw, I'm a bit confused about what you mean by "whenever I click on chrome it opens up with all the windows or activated window but this time it didn't. When I use a mouse it does performs the way it should but with a trackpad, it says no window activated." If you mean the trackpad click doesn't open anything you can go to setting>trackpad> tick the box "tap to click" and turn off "look up& data detector". 

Your config is conflicted with the kernel section, (OC: Prelink injection I2C invalid parameter) Some people faced the same issue but I can't find the real issue. So, I try to write a new config based on my config, and voila! (You may compare with your own config file and figure what things really change!)

Lastly, I forgot to change the boot- arg back to your config, maybe you can delete and add back your own boot-args (bcrm is kinda useless for you as you use stock wifi adapter 😅)

**Comment by yuvrajharod** [comment]
No worries mate and I was able to solve the issue upfront you told me later on by disabling the "Haptic feedback" option I was able to solve it.

Also soon I'm too shifting to the BCM to I think even that would help me to work with it flawlessly when I install it.
Also to write config is there any process written and I can read it, like I followed the guide still faced to is there any better way?

and Also as the issue is resolved, shall I go ahead and close the issue?

Again many many thanks to you and merry Christmas🎄.

**Comment by JoK3rLeE** [comment]
> No worries mate and I was able to solve the issue upfront you told me later on by disabling the "Haptic feedback" option I was able to solve it.
> 
> Also soon I'm too shifting to the BCM to I think even that would help me to work with it flawlessly when I install it.
> Also to write config is there any process written and I can read it, like I followed the guide still faced to is there any better way?
> 
> and Also as the issue is resolved, shall I go ahead and close the issue?
> 
> Again many many thanks to you and merry Christmas🎄.

If you change to bcrm wifi, what you need is inject bcrmfirmware kext into kernel section and of course kext folder! 

Your config is good to go! But if you want to improve your own config, find similar specification devices (Doesn't matter if the processor is 7th Gen or 8th Gen, they share almost the same hardware) You can find it from my README.md  


Happy Festivus! If you have other issue, please don't hesitate to find me :D

**Comment by yuvrajharod** [comment]
Alright unfortunately after applying this I fell in another issue that my speaker doesn't work anymore. they Con8050 and I tried replacing the audio kext but didn't work for me. Dk what went wrong in this one now.

**Comment by yuvrajharod** [comment]
Also after the EFI change I could notice the fan noise more than I was able to. With just normal task. Like as soon as I start!

**Comment by JoK3rLeE** [comment]
If you want your fan to work quietly, maybe you can add back the ACPI file, For audio, that will be a bit tricky and troublesome... what I can suggest is try to use back your old EFI file, and make sure everything works as normal (aside from trackpad). 

or try this config: 
Experimental config (use back your EFI, completely same but replaced kernel section) 
File too big to upload here.. 
https://drive.google.com/file/d/1K_efp2HtxXhFhvaL--oPUTJkSmollcJt/view?usp=sharing
