### ISSUE TITLE
Booting error with S510UQ-BQ216

### ISSUE THREAD

**Issue by minhthong176881** [JoK3rLeE/Asus-S510UQ-BQ178T#3]
Hello,
I'm using Asus-S510UQ-BQ216. I installed macOS successfully, but I tried to use yours EFI to boot into the OS because I saw you patched a lot of stuffs. But I met some problems like bellow. Can you explain for me what the errors are and how to fix them? 
Thanks.

![image](https://user-images.githubusercontent.com/45230933/104090589-517d0d80-52aa-11eb-872c-178b14e53974.png)
xt)

**Comment by JoK3rLeE** [comment]
Hi, I'm sorry for the error you have faced, you need to enable AppleCpuPmCfgLock and AppleXcpmCfgLock in config. It was my mistake for not added in for latest OC. And also my EFI will have some changes soon, maybe you can check back later :) 

here's the new config 
[config.zip](https://github.com/JoK3rLeE/Asus-S510UQ-BQ178T/files/5791168/config.zip)

**Comment by minhthong176881** [comment]
Thank for your response, but I when I tried the new config, it had another issue.  I cannot get into OC select boot option.
It said: "OCS: No schema for De
duplicateBootOrder at 0 index, context <Quirks> |
OC: Driver ExFatDxe.efi at 1 cannot be found |
Halting on critical error"
Is there any additional setups that I need to do?
![image](https://user-images.githubusercontent.com/45230933/104094394-47b3d400-52c3-11eb-81b9-c30f06a42254.png)

**Comment by JoK3rLeE** [comment]
> Thank for your response, but I when I tried the new config, it had another issue. I cannot get into OC select boot option.
> It said: "OCS: No schema for De
> duplicateBootOrder at 0 index, context |
> OC: Driver ExFatDxe.efi at 1 cannot be found |
> Halting on critical error"
> Is there any additional setups that I need to do?
> ![image](https://user-images.githubusercontent.com/45230933/104094394-47b3d400-52c3-11eb-81b9-c30f06a42254.png)

You can't get into OC selection because I didn't apply picker mode, maybe you can try a whole new EFI?
[Asus S510UQ-BQ178T OpenCore 0.6.5 EFI (1).zip](https://github.com/JoK3rLeE/Asus-S510UQ-BQ178T/files/5791278/Asus.S510UQ-BQ178T.OpenCore.0.6.5.EFI.1.zip)

**Comment by minhthong176881** [comment]
> > Thank for your response, but I when I tried the new config, it had another issue. I cannot get into OC select boot option.
> > It said: "OCS: No schema for De
> > duplicateBootOrder at 0 index, context |
> > OC: Driver ExFatDxe.efi at 1 cannot be found |
> > Halting on critical error"
> > Is there any additional setups that I need to do?
> > ![image](https://user-images.githubusercontent.com/45230933/104094394-47b3d400-52c3-11eb-81b9-c30f06a42254.png)
> 
> You can't get into OC selection because I didn't apply picker mode, maybe you can try a whole new EFI?
> [Asus S510UQ-BQ178T OpenCore 0.6.5 EFI (1).zip](https://github.com/JoK3rLeE/Asus-S510UQ-BQ178T/files/5791278/Asus.S510UQ-BQ178T.OpenCore.0.6.5.EFI.1.zip)

I tried the new EFI with an USB and it came up with this message 
![image](https://user-images.githubusercontent.com/45230933/104095807-77ff7080-52cb-11eb-8eac-48d03312d966.png)
And then It booted into my recovery mode in my USB (my com.apple.recovery.boot folder) without showing me the boot selections. But at least It booted successfylly, should I try to replace this EFI directly into my macOS's EFI?

**Comment by JoK3rLeE** [comment]
Hmm maybe try this config ? 
Changes: 
Misc> Boot> Picker attributes set to 3
Misc> Security > BootProtect set to none 


[config.zip](https://github.com/JoK3rLeE/Asus-S510UQ-BQ178T/files/5791397/config.zip)

**Comment by minhthong176881** [comment]
> Hmm maybe try this config ?
> Changes:
> Misc> Boot> Picker attributes set to 3
> Misc> Security > BootProtect set to none
> 
> [config.zip](https://github.com/JoK3rLeE/Asus-S510UQ-BQ178T/files/5791397/config.zip)

I can boot successfully now. Thank you very much. Everything works perfectly <3

**Comment by JoK3rLeE** [comment]
> > Hmm maybe try this config ?
> > Changes:
> > Misc> Boot> Picker attributes set to 3
> > Misc> Security > BootProtect set to none
> > [config.zip](https://github.com/JoK3rLeE/Asus-S510UQ-BQ178T/files/5791397/config.zip)
> 
> I can boot successfully now. Thank you very much. Everything works perfectly <3

Great news! 👍
