### ISSUE TITLE
can't sleep/wake

### ISSUE THREAD

**Issue by Elistasandy** [JoK3rLeE/Asus-S510UQ-BQ178T#4]
hi, I have a problem with sleep and can't wake up (black screen). how to fix it?

Asus S510UQ - Big Sur 11.1

**Comment by JoK3rLeE** [comment]
Hi, your laptop spec also have DGPU? If yes this might be due to a Discrete graphic issue, and I will add a new patch for that.

**Comment by Elistasandy** [comment]
Yeah, it has DGPU. Fortunately, the issue already fixed after I pulling your last commit. THANKS!!

**Comment by JoK3rLeE** [comment]
Glad that your issue fixed :)
