### ISSUE TITLE
ASK: Zenbook UX333FA

### ISSUE THREAD

**Issue by Elistasandy** [JoK3rLeE/Asus-S510UQ-BQ178T#6]
Hi, would you mind to make efi for this laptop?

ASUS ZENBOOK UX333FA
Specifications : 
- Processor : Intel Core i5-8265U
- RAM : 8GB RAM DDR4 PC17000 / 2133Mhz
- Storage : 1x WD Black SSD 256GB
- iGPU : Intel UHD Graphics 620
- Touchpad : ELAN1200 I2C Interface
- Baclight Keyboard : Yes
- Audio Codec : Realtek ALC294
- Wifi : Intel AC 9560
- Ethernet : No Ethernet
- Screen Size : 13.3" IPS
- Screen Resolution : 1920 x 1080

i will sent you original DSDT from OC

**Comment by JoK3rLeE** [comment]
Hi, Your hardware almost the same as mine, I suggest you, Try to use my EFI. For sound codec, you have to change the audio layout-id to 21/22 in config>DeviceProperties section (More Info can be found [here](https://github.com/hieplpvip/Asus-Zenbook-Hackintosh/issues/67)  )

**Comment by Elistasandy** [comment]
> Hi, Your hardware almost the same as mine, I suggest you, Try to use my EFI. For sound codec, you have to change the audio layout-id to 21/22 in config>DeviceProperties section (More Info can be found [here](https://github.com/hieplpvip/Asus-Zenbook-Hackintosh/issues/67) )
> 
> or you may try this EFI
> [EFI.zip](https://github.com/JoK3rLeE/Asus-S510UQ-BQ178T/files/5861851/EFI.zip)

I already try using EFI that you gave, but got a problem. please see the attachment bellow


![image](https://user-images.githubusercontent.com/28147702/105632071-fd665180-5e83-11eb-8f4e-3ceb351cd88e.png)

**Comment by JoK3rLeE** [comment]
Seems like ELAN issue. 

can you try this EFI?
[EFI (1).zip](https://github.com/JoK3rLeE/Asus-S510UQ-BQ178T/files/5862427/EFI.1.zip)

**Comment by Elistasandy** [comment]
> Seems like ELAN issue.
> 
> can you try this EFI?
> [EFI (1).zip](https://github.com/JoK3rLeE/Asus-S510UQ-BQ178T/files/5862430/EFI.1.zip)

I have tried that one but seems like there is another error occurred


![image](https://user-images.githubusercontent.com/28147702/105633791-48389700-5e8d-11eb-8b2f-7981e1da4891.png)

**Comment by JoK3rLeE** [comment]
Ok... can you try the last EFI ? 
If still unable to work, then I can't do anything on that as I don't have the same specification laptop to debug. 

[EFI (Based on UX430).zip](https://github.com/JoK3rLeE/Asus-S510UQ-BQ178T/files/5862604/EFI.Based.on.UX430.zip)

**Comment by Elistasandy** [comment]
Unfortunately, it won’t works on my laptop, but thanks for the time and your help on my case. 
Btw I have a friend that succeed to run hackintosh with the same specifications as mine but his EFI already patch on DSDT. I don’t know how to change it to SSDT patch in order to work on my laptop.

**Comment by JoK3rLeE** [comment]
> Unfortunately, it won’t works on my laptop, but thanks for the time and your help on my case.
> Btw I have a friend that succeed to run hackintosh with the same specifications as mine but his EFI already patch on DSDT. I don’t know how to change it to SSDT patch in order to work on my laptop.

Do you have your friend DSDT patch? Maybe I can have a quick look. also, you may dump your full dsdt and send it to my personal email: jok3rle3@gmail.com

**Comment by Elistasandy** [comment]
Alright, I’ve sent you the DSDT. Please check it when you are free. Thanks a lot!
