### ISSUE TITLE
Ask: Connect to external monitor with HDMI

### ISSUE THREAD

**Issue by minhthong176881** [JoK3rLeE/Asus-S510UQ-BQ178T#8]
Hi, I am using Asus-S510UQ-BQ216. I want to connect my laptop with external monitor through HDMI port to use both screens, but it only displays on 1 monitor (if it on the external one, the laptop screen is black and vice versa) and it doesn't have Arrangement tab in Displays setting. Can you help me with this case?
Thank you.

**Comment by JoK3rLeE** [comment]
Hi, You may try with whatnameisit config or you can try with the EFI below. I personally doesn't have issue with external monitor through HDMI 
![Screen Shot 2021-03-19 at 2 24 01 AM](https://user-images.githubusercontent.com/28730136/111677450-35718b80-885a-11eb-9741-3920df0f815a.png)
[EFI.zip](https://github.com/JoK3rLeE/Asus-S510UQ-BQ178T/files/6166451/EFI.zip)

**Comment by minhthong176881** [comment]
Hi, I tried your EFI and it worked. But can I ask you that which part that the issue related to (such as ACPI, kext, drivers,... )?

**Comment by JoK3rLeE** [comment]
Config under device properties: PciRoot(0x0)/Pci(0x2,0x0)

**Comment by minhthong176881** [comment]
I checked and mine config is the same with yours but it only works with your config 
![image](https://user-images.githubusercontent.com/45230933/111735699-0a655700-88af-11eb-949f-9417a0c686b3.png)

**Comment by JoK3rLeE** [comment]
> I checked and mine config is the same with yours but it only works with your config
> ![image](https://user-images.githubusercontent.com/45230933/111735699-0a655700-88af-11eb-949f-9417a0c686b3.png)

Maybe due to your platformInfo doesn't have generic section (I checked with my git and realized that I uploaded incomplete platform info that doesn't have valid System Product name.) 

You can compare both: PlatformInfo> Generic
